### ISSUE TITLE
Incorrect documentation for getProps

### ISSUE THREAD

**Issue by Biohazord** [Workable/backbone.react-bridge#4]
In the example for `viewFromComponent` the method `getProps` calls `this.collection` while `this` is not defined.  After looking at the source it appears as though `getProps` actually receives `options` as an argument. To get the example working the method should be

```
getProps({collection}) {
      return {
        titles: collection.map((m) => {title: m.get('title').toUpperCase()})
      }
    }
```

**Comment by Biohazord** [comment]
I'm not sure how to properly link PRs on github so I'm just leaving a link here. Sorry it isn't cleaner. https://github.com/Workable/backbone.react-bridge/pull/5

**Comment by imktks** [comment]
You are right! Thanks @Biohazord, i left a comment in the PR

**Comment by imktks** [comment]
Resolved in https://github.com/Workable/backbone.react-bridge/pull/5
